<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');
?>
<style>.newsform {
    background: #A3A5A4;
    color: #fff;
}</style>
<div class="block newsletter" style="width: auto;">
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="footer_newsletter"><span><?php echo __('Sign Up for Our Newsletter:') ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="footer_newsletter"
                                data-validate="{required:true, 'validate-email':true}" placeholder="<?php echo __('Email Address');?>"/>
                </div>
            </div>
            <div class="actions" style="width: auto;display: contents;">


                <button class="action subscribe primary" title="<?php echo __('Subscribe') ?>" type="submit" style="width: inherit;width: 100%;border-radius: 10px;background-color: #2669b3;margin-top: 35px;">
                    <span><?php echo __('Subscribe') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
